version: "3.8"
networks:
  eureka-net:
    driver: bridge
services:
  service-eureka:
    image: amourabarreto/microservices:service-registry
    container_name: service-registry
    networks:
      - eureka-net
    ports:
      - "8761:8761"
    env_file:
      - service-registry.env
  service-gateway:
    image: service-gateway:latest
    container_name: service-gateway
    networks:
      - eureka-net
    ports:
      - "8080:8080"
    env_file:
      - service-gateway.env
    depends_on:
      - service-eureka
  config-server:
    image:  config-server:latest
    container_name: config-server
    networks:
      - eureka-net
    ports:
      - "8888:8888"
    env_file:
      - config-server.env
    depends_on:
      - service-eureka
  postgres:
    image: postgres
    container_name: postgres
    networks:
      - eureka-net
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: adm123
    volumes:
      - "c:/dev/volumes/postgres/data:/var/lib/postgresql/data"
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "c:/Dev/volumes/rabbitmq/data:/var/lib/rabbitmq"
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.2.2
    container_name: filebeat
    user: root
    volumes:
      - "C:/Dev/volumes/filebeat/conf/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro"
      - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "C:/Dev/java/IdeaProjects/microservices/decoder/authuser/logs/ead-authuser-service.log:/var/log/ead-authuser/ead-authuser-service.log:ro"
    command: --strict.perms=false
  keycloak:
    build:
      context: .
      dockerfile: Dockerfile-keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      - postgres
    ports:
      - "9090:8080"
    container_name: keycloak_server_18
    networks:
      - eureka-net
  wildfly:
    image: quay.io/wildfly/wildfly:latest-jdk17
    container_name: wildfly
    volumes:
      - "C:/Dev/volumes/wildfly:/opt/jboss/wildfly/standalone/deployments/:ro"
    restart: always
    command: >
      bash -c "/opt/jboss/wildfly/bin/add-user.sh admin Admin#007 --silent
      && /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0 --debug"
    networks:
      - eureka-net
    ports:
      - "8082:8080"
      - "9990:9990"
      - "8787:8787"