version: "3.8"
networks:
  eureka-net:
    driver: bridge
services:
  service-eureka:
    image: amourabarreto/microservices:service-registry
    container_name: service-registry
    networks:
      - eureka-net
    ports:
      - "8761:8761"
    env_file:
      - service-registry.env
  service-gateway:
    image: service-gateway:latest
    container_name: service-gateway
    networks:
      - eureka-net
    ports:
      - '8080:8080'
    env_file:
      - service-gateway.env
    depends_on:
      - service-eureka
  config-server:
    image:  config-server:latest
    container_name: config-server
    networks:
      - eureka-net
    ports:
      - 8888:8888
    env_file:
      - config-server.env
    depends_on:
      - service-eureka
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: adm123
    volumes:
      - "c:/dev/volumes/postgres/data:/var/lib/postgresql/data"
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - "c:/Dev/volumes/rabbitmq/data:/var/lib/rabbitmq"