version: "3.8"
networks:
  eureka-net:
    driver: bridge
services:
  service-eureka:
    image: amourabarreto/microservices:service-registry
    container_name: service-registry
    networks:
      - eureka-net
    ports:
      - "8761:8761"
    environment:
      USERNAME: admin
      PASSWORD: admin
  service-gateway:
    image: amourabarreto/microservices:service-gateway
    container_name: service-gateway
    networks:
      - eureka-net
    ports:
      - '8080:8080'
    environment:
      EUREKA-SERVER: service-eureka
      USERNAME-EUREKA: admin
      PASSWORD-EUREKA: admin
      USERNAME-CONFIG-SERVER: admin
      PASSWORD-CONFIG-SERVER: admin
    depends_on:
      - service-eureka
  config-server:
    image:  amourabarreto/microservices:config-server
    container_name: config-server
    networks:
      - eureka-net
    ports:
      - 8888:8888
    environment:
      USERNAME: admin
      PASSWORD: admin
      USERNAME-GIT: amourabarreto
      PASSWORD-GIT: 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
      URI:  https://github.com/amourabarreto/ead-config-server-repo
      EUREKA-SERVER: service-eureka
      USERNAME-EUREKA: admin
      PASSWORD-EUREKA: admin
    depends_on:
      - service-eureka
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: adm123
    volumes:
      - "c:/dev/volumes/postgres/data:/var/lib/postgresql/data"
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - "c:/Dev/volumes/rabbitmq/data:/var/lib/rabbitmq"